auction/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'auction.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'', include('social_auth.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls', namespace='account')),

    url(r'^', include('core.urls', namespace='core')),
)

from auction import settings
urlpatterns += patterns('',
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

core/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studyplan.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.index, name='index'),
)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>유니스트 팜</title>

    <!--
    start : 2014-07-30 05:30 pm
                                   _           ____   ___
      ___ __ _ _ __ _ __   ___  __| |_ __ ___ |___ \ / _ \
     / __/ _` | '__| '_ \ / _ \/ _` | '_ ` _ \  __) | | | |
    | (__ (_| | |  | |_) |  __/ (_| | | | | | |/ __/| |_| |
     \___\__,_|_|  | .__/ \___|\__,_|_| |_| |_|_____|\___/
                   |_|

    end  : 2014-??-??
    -->

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300&subset=latin,greek' rel='stylesheet'>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.less' %}" rel="stylesheet/less" type="text/css">

    <script src="{% static 'js/d3.min.js' %}"></script>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="{% static 'js/html5shiv.js' %}"></script>
      <script src="{% static 'js/respond.min.js' %}"></script>
    <![endif]-->
  </head>

  <body>
    {% include 'navbar.html' %}

    <div id="main">
      <div class="container">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
              {{ message }}
              <button class="close" onclick="$('.alert').hide();">×</button>
            </div>
          {% endfor %}
        {% endif %}

        {% block content %} {% endblock %}
      </div>
    </div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/less.js/1.7.0/less.min.js"></script>
  </body>
</html>

templates/card.html
{% load humanize %}

<div class="col-xs-6 col-xs-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="panel-title">{{ request.user.korean_name }} 님의 도전</h2>
    </div>
    <div class="panel-body">
      <form action="{% url 'core:index' %}" method="post">
        {% csrf_token %}
        <div class="input-group col-xs-12">
          <div class="input-group-addon">#</div>
          {% if disabled %}
            <input type="text" class="form-control" name="reason" value="{{ deal.reason }}" disabled>
          {% else %}
            <input type="text" class="form-control" name="reason" placeholder="한줄 구매 사유">
          {% endif %}
        </div>
        <div class="checkbox">
          <label>
            <input type="checkbox" name="is_name_filter"> 이름 일부 가리기
          </label>
        </div>
        <div class="input-group input-group-lg">
          <input type="number" class="form-control" name="value" placeholder="최소 {{ stuff.recent_price|add:stuff.min_diff_price|intcomma}} 원 이상">
          <span class="input-group-btn">
            <button class="btn btn-default" type="submit">Go!</button>
          </span>
        </div>
      </form>
    </div>
  </div>
</div>

templates/index.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% load humanize %}

{% block content %}

<section id="auction">
<div class="stuff-bg" style="background-image: url({{ stuff.img_url }});"></div>

<div class="stuff">
  <div class="stuff-detail text-center">
    <h1 class="title">{{ stuff.name }}</h1>
    <h4 class="detail"><span class="label label-default">{{ stuff.detail }}</span></h4>
    <button class="btn btn-primary btn-lg" disabled>시작 가격 : {{ stuff.start_price|intcomma }} 원</button>
    <button class="btn btn-danger btn-lg">현재 가격 : {{ stuff.recent_price|intcomma }} 원</button>
  </div>
  <div class="deal">
    {% if user.is_authenticated %}
      {% include 'card.html' with disabled=False %}
      {% for deal in stuff.deal_set.all %}
        {% include 'card.html' with disabled=True deal=deal %}
      {% endfor %}
    {% else %}
      <div class="fb-join"> 
        <a href="{% url 'socialauth_begin' 'facebook' %}" onclick="window.open(this.href,'targetWindow','toolbar=no,location=no,status=no,menubar=no,scrollbars=yes,resizable=yes,width=400,height=300');return false;">
          <div class="fb-join-image"><img src="https://d3kif4no5sfwzt.cloudfront.net/assets/intro/intro_btn_fb-86680a3702eb0c41f5cf6412554e2360.png"></div>
          <div class="fb-join-text">페이스북으로 로그인</div>
        </a>
      </div>
    {% endif %}
  </div>
</div>


</section>

{% endblock %}

templates/navbar.html
{% load staticfiles %}

<nav class="navbar navbar-fixed-top header">
  <div class="container">
    <div class="navbar-header">
      <a href="{% url 'core:index' %}" class="navbar-brand">유니스트 팜</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <!--<li class="active"><a href="#">Home</a></li>-->
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">About</a></li>
      </ul>
    </div>  
  </div>
</nav>

templates/practice.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% load staticfiles %}

{% block content %}

<div id="practice"></div>
<section id="section"></section>
<div id="barChart"></div>
<br/>
<svg class="chart"></svg>
<br/>
<svg class="chart2"></svg>
<br/>
<svg class="chart3"></svg>

<style>
#barChart div {
  font: 10px sans-serif;
  background-color: steelblue;
  text-align: right;
  padding: 3px;
  margin: 1px;
  color: white;
}
.chart rect, .chart2 rect, .chart3 rect{
  fill: steelblue;
}

.chart text, .chart2 text, .chart3 text {
  fill: white;
  font: 10px sans-serif;
  text-anchor: end;
}

.bar:hover {
  fill: brown;
}

.axis text {
  font: 10px sans-serif;
}

.axis path,
.axis line {
  fill: none;
  stroke: #000;
  shape-rendering: crispEdges;
}

.x.axis path {
  display: none;
}

</style>

<script>
  /******************************************************
     http://mbostock.github.com/d3/tutorial/circle.html
  ******************************************************/

  var width = 720;
  var height = 120;

  var minWidthHeight = Math.min(width, height);

  var practice = d3.select("#practice")
    .append("svg:svg")
    .attr("width", width)
    .attr("height", height);

  var data = [40, 80, 120];

  // "circle" : `selector` string
  // practice.selectAll(`selector`) : `selection`

  practice.selectAll("circle") // selection
    .data(data)
    .enter()
    .append("svg:circle")
    .attr("cx", function(d) { return d; })
    .attr("cy", height/2)
    .attr("r", minWidthHeight/12);

  var circle = d3.selectAll("circle");

  circle.style("fill", "steelblue");
  circle.attr("r", minWidthHeight/4);

  circle.attr("cx", function() { return Math.random() * width; });
  circle.attr("r", function(d) { return Math.sqrt(d); });
  circle.attr("cx", function(d, i) { return i * 100 + 30; });

  var circle = practice.selectAll("circle").data([40, 120]);
  circle.exit().remove();

  /******************************************************
     http://mbostock.github.com/d3/tutorial/bar-1.html
  ******************************************************/

  var data = [4, 8, 15, 16, 23, 42];

  var body = d3.select("body");
  var div = body.append("div");
  //div.html("Hello, world!");

  var section = d3.selectAll("#section");
  var div = section.append("div");
  div.html("Hello, world!!");

  body.style("color", "black");
  body.style("background-color", "white");

  d3.select("body")
    .style("color", "black")
    .style("background-color", "white");

  d3.selectAll("#section")
    .attr("class", "special")
    .append("div")
    .html("Hello World!!!")

  var section = d3.selectAll("#section");
  section.append("div").html("First!");
  section.append("div").html("Second.");

  var barChart = d3.select("#barChart");
  var height = 200;

  barChart.selectAll("div")
    .data(data)
    .enter().append("div")
    .style("width", function(d) { return d * 10 + "px"; })
    .text(function(d) { return d; });

  var x = d3.scale.linear()
    .domain([0, d3.max(data)])
    .range([0, width]);

  var y = d3.scale.linear()
    .domain([0, data.length])
    .range([0, height]);

  var barHeight = y(1);

  var chart = d3.select(".chart")
    .attr("width", width)
    .attr("height", barHeight * data.length);

  var bar = chart.selectAll("g")
    .data(data)
    .enter().append("g")
    .attr("transform", function(d, i) { return "translate(0," + y(i) + ")"; });

  bar.append("rect")
    .attr("width", x)
    .attr("height", barHeight - 1);

  bar.append("text")
    .attr("x", function(d) { return x(d) - 3; })
    .attr("y", barHeight / 2)
    .attr("dy", ".35em")
    .text(function(d) { return d; });


  height = 110;

  var x = d3.scale.linear()
    .range([0, width]);

  var y = d3.scale.linear()
    .range([0, height]);

  var chart = d3.select(".chart2")
    .attr("width", width);
  
  var tsvData = [];

  var data = [
    {name: "Locke",    value:  4},
    {name: "Reyes",    value:  8},
    {name: "Ford",     value: 15},
    {name: "Jarrah",   value: 16},
    {name: "Shephard", value: 23},
    {name: "Kwon",     value: 42}
  ];

  x.domain([0, d3.max(data, function(d) { return d.value; })]);
  y.domain([0, data.length]);

  chart.attr("height", height);

  var barHeight = y(1);

  var bar = chart.selectAll("g")
    .data(data)
    .enter().append("g")
    .attr("transform", function(d, i) { return "translate(0, " + y(i) + ")"; });

  bar.append("rect")
    .attr("width", function(d) { return x(d.value); })
    .attr("height", barHeight - 1);

  bar.append("text")
    .attr("x", function(d) { return x(d.value) - 3; })
    .attr("y", barHeight/2)
    .attr("dy", ".35em")
    .text(function(d) { return d.value; });

  function type(d) { 
    d.value = +d.value;
    return d;
  }

  var data = [
    {"name": "A", "value": 0.08167},
    {"name": "B", "value": 0.01492},
    {"name": "C", "value": 0.02782},
    {"name": "D", "value": 0.04253},
    {"name": "E", "value": 0.12702},
    {"name": "F", "value": 0.02288},
    {"name": "G", "value": 0.02015},
    {"name": "H", "value": 0.06094},
    {"name": "I", "value": 0.06966},
    {"name": "J", "value": 0.00153},
    {"name": "K", "value": 0.00772},
    {"name": "L", "value": 0.04025},
    {"name": "M", "value": 0.02406},
    {"name": "N", "value": 0.06749},
    {"name": "O", "value": 0.07507},
    {"name": "P", "value": 0.01929},
    {"name": "Q", "value": 0.00095},
    {"name": "R", "value": 0.05987},
    {"name": "S", "value": 0.06327},
    {"name": "T", "value": 0.09056},
    {"name": "U", "value": 0.02758},
    {"name": "V", "value": 0.00978},
    {"name": "W", "value": 0.02360},
    {"name": "X", "value": 0.00150},
    {"name": "Y", "value": 0.01974},
    {"name": "Z", "value": 0.00074}
  ];

  var width=960, height=500;

  var margin = {top: 20, right: 30, bottom: 30, left: 40},
    width = width - margin.left - margin.right,
    height = height - margin.top - margin.bottom;

  var x = d3.scale.ordinal()
    .rangeRoundBands([0, width], .1);

  var y = d3.scale.linear()
    .range([height, 0]);

  var xAxis = d3.svg.axis()
    .scale(x)
    .orient("bottom");

  var yAxis = d3.svg.axis()
    .scale(y)
    .orient("left")
    .ticks(10, "%");

  var chart = d3.select(".chart3")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
    .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

  x.domain(data.map(function(d) { return d.name; }));
  y.domain([0, d3.max(data, function(d) { return d.value; })]);

  chart.append("g")
    .attr("class", "x axis")
    .attr("transform", "translate(0, " + height + ")")
    .call(xAxis);

  chart.append("g")
    .attr("class", "y axis")
    .call(yAxis)
    .append("text")
    .attr("transform", "rotate(-90)")
    .attr("y", 6)
    .attr("dy", ".71em")
    .style("text-anchor", "end")
    .text("Frequency");

  var bar = chart.selectAll(".bar")
    .data(data)
    .enter().append("rect")
    .attr("class", "bar")
    .attr("x", function(d) { return x(d.name); })
    .attr("y", function(d) { return y(d.value); })
    .attr("height", function(d) { return height - y(d.value); })
    .attr("width", x.rangeBand());

</script>

{% endblock %}